### ISSUE TITLE
Access to full Cobra SDK

### ISSUE THREAD

**Issue by jedelman8** [datacenter/cobra#83]
Hello, can someone let me know where I can get Cobra?

I'm using dCloud and the .egg files don't seem to be on the APIC simulator here: /cobra/_downloads/acicobramodel.egg and here: /cobra/_downloads/acicobrasdk.egg

I also tried installing via pip and no distributions are found to download.

Have not yet cloned this repo because I do not see see the the model package, only the SDK.

Can you please advise?

Thanks,
Jason

**Comment by tigelane** [comment]
You can find instructions here:
http://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/1-x/api/python/install/b_Install_Cisco_APIC_Python_SDK_Standalone.html

The short version is:
Both packages are required. You can download the two .egg files from a running instance of APIC at these URLs:

http[s]://<APIC address>/cobra/_downloads/acicobrasdk.egg
http[s]://<APIC address>/cobra/_downloads/acicobramodel.egg

**Comment by mtimm** [comment]
Hi Jason,

What version of APIC code is running in dCloud?  

There was a Cisco bug filed for getting cobra on to the simulator [CSCus15670 - Python SDK Docs and eggs should be included on the APIC simulator](https://tools.cisco.com/bugsearch/bug/CSCus15670).  It should be resolved 1.0(3*).

The SDK will eventually go on pypi but at this point in time there are few minor roadblocks to making that happen.  Until then pip will not find the SDK automatically.

The model is also being put on github and eventually pypi as well but there was a hold-up with the license it was to be released under.  Also the way the cobra model is structured is being completely overhauled, primarily for performance reasons.  I tested that overhaul last night and there are just one or two open questions I need to resolve before we move forward with it.

We also need to redo our documentation on installation.  For now, I wouldn't say the github version is ready for primetime.  Instead the eggs are available in a somewhat easy to install manner starting in 1.0(3*):

```
easy_install -Z --find-links https://<apic>/cobra/_downloads acicobra
easy_install -Z --find-links https://<apic>/cobra/_downloads acimodel
```

For a simulator running 1.0(2*) or earlier, things get a bit more complicated and a call to Cisco TAC might be the best way forward.

Hopefully all this will be resolved soon when the SDK and model are both available on pypi.

Mike

**Comment by jedelman8** [comment]
It is version: 1.0(3f).  I'm getting 404 responses back for each.  Should the egg files be there?

So there isn't any other way to get the SDK then?  That seems really odd.  Can you post them to this repo?

Thanks.

**Comment by mtimm** [comment]
Hi Jason,

With version 1.0(3f) you should be able to use the easy_install commands I posted before.

```
easy_install -Z --find-links https://<apic>/cobra/_downloads acicobra
easy_install -Z --find-links https://<apic>/cobra/_downloads acimodel
```

Here's the full history:
- In 1.0(1*) there was only one egg and it was not included on the APIC or the simulator.  You can download it from the Cisco.com downloads page, it is listed along with the APIC software.
- In 1.0(2*) there are two eggs and there was an attempt to put them on the APIC, however the simulator was missed.  In addition, how the eggs were added to the APIC was to rename the files from their normal names to acicobrasdk.egg and acicobramodel.egg.  However, renaming them this way causes issues with the python packaging utilities easy_install and pip.  You can install them once they are downloaded but uninstall was not so simple unless you renamed the eggs back to their normal names.
- In 1.0(3*) the eggs are included on the APIC and the simulator and can be directly installed using easy_install or downloaded first and installed from a local file.  The eggs are not named acicobrasdk.egg and acicobramodel.egg in 1.0(3f).  Instead they are named acicobra-1.0_3f-py2.7.egg and acimodel-1.0_3f-py2.7.egg.  Keeping the version info in the egg filename allows pip to uninstall them if needed.

In the future the sdk and model will be on pypi and versioned so it will be as simple as installing any python package.

Sorry this is so convoluted but just getting permission to put this stuff on github was a major chore, now we are working to improve the install process and hope to have that wrapped up soon.

Please do let me know if you have any questions or run into other issues.

Hope that helps,

Mike

**Comment by jedelman8** [comment]
Mike,

This is what I'm seeing:

```
cisco@onepk:~/ACI$ sudo easy_install -Z --find-links http://198.18.133.200/cobra/_downloads acicobra
/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'xdiagnose (3.6.3build2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'python-debian (0.1.21-nmu2ubuntu2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
Searching for acicobra
Reading http://198.18.133.200/cobra/_downloads
Reading https://pypi.python.org/simple/acicobra/
Couldn't find index page for 'acicobra' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'getpaid.recipe.release (fix)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
No local packages or download links found for acicobra
error: Could not find suitable distribution for Requirement.parse('acicobra')
```

Have also tried using https and get other errors regarding certificates.  APIC has http enabled.  Have tried browsing natively and still get 404 errors.

Have a shot yourself :)

Anyconnect:  dcloud-rtp-anyconnect.cisco.com
username: v471user16
pw: 83917e

APIC: 198.18.133.200

Please let me know what I am screwing up!

Thanks,
Jason

**Comment by mtimm** [comment]
Hi Jason,

I've checked the simulator you have access to in dcloud and it certainly is missing the cobra docs and SDK.  I believe dCloud is running an OVA version of the simulator which is currently built outside of the normal APIC build process.  I'm setting up a dCloud demo instance for myself to verify and will get back to you about what I find.

In addition there are other issues we need to address with where the SDK is currently available on Cisco.com but the model portion of it is not.  I'm working to get that addressed now.

Thanks!

Mike

**Comment by mtimm** [comment]
Hi Jason,

Ok I stand corrected, this is a VM version of the simulator but not the OVA.  Let me look into this a bit more but it would seem to me that the bug I mentioned before is only fixed for the hardware simulator, not the VM simulator which is wrong.  If that's the case I'll end up having to file another bug.

Regarding dcloud specifically, the labs have no dependency on the sdk/model packages.  However they are available on the TOOLS linux system in user01 home directory and can be directly installed from there:

```
easy_install -Z ./acicobra-1.0_3f-py2.7.egg
easy_install -Z ./acimodel-1.0_3f-py2.7.egg
```

Mike

**Comment by mtimm** [comment]
Hi Jason,

I found the root of my confusion.  I tested a private build from the developer which was built based on the code that would eventually become 1.0(3_) but the fix it self went into 1.1(0_).  So the simulator is not expected to have the SDK and documentation for the SDK until 1.1(0*).  

I will keep working to get the sdk and model posted at least to cisco.com until we have them on pypi.

Mike

**Comment by jedelman8** [comment]
Hi Mike,

Thanks for the detailed response.  I will try using the SDK from the tools VM as you suggested later today.  Will keep you posted on how this goes.

At a minimum, if there are issues posting the source code, why can you not just post the eggs to GitHub?

And on a side note, if the SDK is not on PyPi yet, it probably makes sense to remove those install instructions from the GitHub readme.  Definitely misleading.

Thanks,
Jason

**Comment by mtimm** [comment]
Hi Jason,

A bug was already opened for not having the model package on Cisco.com, so the process to get that fixed is underway.

Why we can't post this stuff to github right now:
1.  The proper place for the eggs is pypi.  Github can host zip files fairly easily but managing the eggs in a git repo is not ideal.
2.  There are licensing concerns.  I'm not intimately familiar with what this concerns are but we are waiting for lawyers to work things out and provide a license (specifically for the model package) that those lawyers are happy with.

Mike

**Comment by mtimm** [comment]
An update on this - still a work in progress.

We have a license specific for the acimodel.  The big hang up right now seems to be a requirement for positive acknowledgement of the license on install which is not something that pip or easy_install can easily do today (there is a bug/enhancement request already for one of them for other packages that have the same requirement).  

So more than likely the process for getting the model outside of cisco.com and an APIC will likely be:
1. Post it to github under https://github.com/datacenter/acimodel (this is currently a private repo but could be opened up).
2. To install you would download the zip or clone the repo.
3. Then do, `python setup.py install`
4. During the installation you will be asked to accept the license.  If you accept the install goes through, if you don't accept the install does not go through.

This is just the thought of how it might work and I'm certainly open to suggestions but keep in mind we are working within the restrictions being provided by a licensing lawyer.  We are also exploring the idea of not requiring a model package be installed and instead download the required items at runtime.  I'm not sure how that will work yet but it is one thing we are looking at.

**Comment by jedelman8** [comment]
That seems just wrong especially with how _open_ things are getting throughout the industry.

**Comment by jedelman8** [comment]
So what is the proper way to get cobra TODAY?  Customer has to go through account team, etc. ?

**Comment by mtimm** [comment]
Download it from the APIC via:

```
http[s]://<apic>/cobra/_downloads
```

Depending on your version of the APIC software there are some caveats.  For example 1.0(1_) did not have cobra on the APIC.  Also 1.0(2_) had the egg files but they were not named properly, the version info was dropped from the name which causes pip to be confused.

If you have a recent version of python, curl that supports TLSv1.1/TLSv1.2, then you can even easy_install right from the APIC:

```
easy_install -Z --find-links https://<apic>/cobra/_downloads acicobra
easy_install -Z --find-links https://<apic>/cobra/_downloads acimodel
```

Most of the time though I've found that easy_install fails here unless http is used because of ssl/tls issues with HTTPS.  You can enable http on the APIC in the Fabric -> fabric policies -> pod policies -> communication section of the GUI then use:

```
easy_install -Z --find-links http://<apic>/cobra/_downloads acicobra
easy_install -Z --find-links http://<apic>/cobra/_downloads acimodel
```

**Comment by bryfry** [comment]
- Is the acicobra egg generated from this repository?
- Are there specific commits of this repository that map to released versions?

I'm okay with the pypy roadblocks but it would be nice to be able to match up this repository with the version of code being shipped with the APIC.

Thanks for any info!

**Comment by mtimm** [comment]
@bryfry There is an effort that is slowly happening to synchronize and consolidate the Cisco internal Cobra code and the public github Cobra repo.  Cobra is now used heavily within the product so it's importance has grown.  Unfortunately as the public repo is open source it is sort of a pet project for those working on it and as such it may not get the attention it needs while other projects take precedence.  

The acicobra egg can be generated from this repo and it should work for the most part.  The latest changes are in the develop branch.  However, be aware that this is not the one shipped on the APIC which is generated from an internal repository.

When a major release goes out, I have been porting commits over to the public repo when I have time.  I have not had time for 1.2 yet.  They all go into the develop repo and then we merge them to master at some point.  

There are major changes potentially coming not only as part of the 1.2 release but after that.  I'm advocating for them being non-breaking changes.

Hope that helps,

Mike

**Comment by bryfry** [comment]
@mtimm Currently this [repo documentation](https://github.com/datacenter/cobra/blob/af99e4fd431369e5a1b1253fd07618578e50ee1e/README.md#install) points to the [APIC+egg](http://cobra.readthedocs.org/en/latest/install.html) documentation.  The split between internal and public is completely understandable but it would be very nice to see the version and corresponding build+usage for this public repo and the target APIC versions it is compatible with.

Definitely appreciate your work getting this code out there!

**Comment by jedelman8** [comment]
Love the cobra code for sure, but I disagree with the statement that "the
split between internal and public is completely understandable"  :)

Just my 2 cents.

**Comment by jedelman8** [comment]
I just started using the ACI 1.2 emulator and scripts I wrote last year using Cobra (1.0) aren't working. Well, some are and some aren't.  Is it just an upgrade of the cobra sdk I need b/c my scripts are still running the old version of cobra but I'm testing against ACI 1.2 if that makes sense.

**Comment by NathanDotTo** [comment]
Hi all

I am trying to use the 1.3 ACI Simulator for the L@C network programming training development. Cobra is not available from that simulator either.

How can we get the egg files given that we are working for Cisco please?

Many thanks

Nathan

**Comment by robphoenix** [comment]
Is there any update on whether this is going to be available via `pip`?

**Comment by clay584** [comment]
Why can we still not pip install the cobra packages? When is Cisco going to publish these? Breaks my module installation because I cannot use requirements file. It's not like anyone can use cobra without buying ACI anyway. It's been four years since this was requested. If you aren't going to do it, just say so and close the issue.
